### ISSUE TITLE
-S and -M flags

### ISSUE THREAD

**Issue by ubermunchen** [TiBeN/m3uragen#1]
Could you please give an example of how to use the -S and -M flags. Is it possible to use them while also using -z?

**Comment by TiBeN** [comment]
Hi,

Yes theses options work with zipped collections too (which are unzipped during process anyway).

On non zipped collections, image files are moved from the original romset path specified. On zipped collection, they are moved from the path specified with the "-z" option (where they are unzipped).

Suppose you have a zipped c64 disks romset and you want to move multi-images files only to another dir:

    $ m3uragen /c64-zipped-files /c64-m3u -z /c64-unzipped -M /c64-multi-images

Then you'll have:

    /c64-zipped-files: original zipped files, left untouched
    /c64-m3u: generated M3U files
    /c64-unzipped: unzipped disk files, containing only singles image files (because multi ones are moved) 
    /c64-multi-images: unzipped disk files, containing only multi-image files

 If you add `-S /c64-singles-images` to move single images, then the `/c64-unzipped` will be empty.

**Comment by TiBeN** [comment]
I close the issue.

Feel free to reopen if you need help
